/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MyContractV1 } from "./MyContractV1";
export type { MyContractV2 } from "./MyContractV2";

export { MyContractV1__factory } from "./factories/MyContractV1__factory";
export { MyContractV2__factory } from "./factories/MyContractV2__factory";
