import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Web3Provider from './utils/web3-provider'
import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3Provider>
          <div>
            <Header/>
            {children}
          </div>
        </Web3Provider>
      </body>
    </html>
  )
}
